name: cp3_devcontainer
channels:
 - pytorch
 - conda-forge
 - metric-learning
 - pyg
dependencies:
 - python=3.8.13
 - pytorch=1.11.0
 - pytorch-metric-learning=1.3.0
 - torchmetrics=0.6.0
 - cudatoolkit=11.3.1
 - pytorch-lightning=1.4.9
 - jupyter
 - pystackreg
 - pyg
 - pip
 - pip:
   - scipy
   - opencv-python-headless
   - opencv-python==4.1.2.30
   - scikit-image
   - diplib
   - matplotlib
   - smo
   - nd2reader
   - seaborn
   - numpy==1.22.4
   - natsort
   - tifffile==2022.5.4
   - tqdm
   - numba>=0.53.0
   - llvmlite
   - mahotas
   - fastremap
   - imagecodecs
   - pyqtgraph>=0.11.0rc0
   - google-cloud-storage
   - sphinx>=3.0
   - sphinxcontrib-apidoc
   - sphinx_rtd_theme
   - dask
   - dask_image
   - record-keeper
   - faiss-gpu #faiss-cpu (on windows)
   - python-dotenv
   - hydra-core==1.1.0.dev5
   - wandb
   - rich
   - cellpose[gui]
   - pandas==1.4.3
   - nd2
 
 
