name: cp_dock
channels:
 - nvidia/label/cuda-12.4.1
 - nvidia
 - pyg
 - pytorch
 - conda-forge
 - metric-learning
dependencies:
 - python=3.8.13
 - cuda-toolkit
 - pytorch=2.4.1
 - torchvision=0.19.1
 - torchaudio=2.4.1
 - pytorch-cuda=12.4
 - pytorch-metric-learning=1.3.0
 - torchmetrics=0.6.0
 - pytorch-lightning=1.4.9
 - pyg
 # - https://anaconda.org/pyg/pyg/2.6.1/download/linux-64/pyg-2.6.1-py38_torch_2.4.0_cu124.tar.bz2
 # - pytorch-sparse
 # - https://anaconda.org/pyg/pytorch-sparse/0.6.18/download/linux-64/pytorch-sparse-0.6.18-py38_torch_2.4.0_cu124.tar.bz2
 # - pytorch-cluster
 # - https://anaconda.org/pyg/pytorch-cluster/1.6.3/download/linux-64/pytorch-cluster-1.6.3-py38_torch_2.4.0_cu124.tar.bz2
 # - pytorch-scatter
 # - https://anaconda.org/pyg/pytorch-scatter/2.1.2/download/linux-64/pytorch-scatter-2.1.2-py38_torch_2.4.0_cu124.tar.bz2
 # - pytorch-spline-conv
 # - https://anaconda.org/pyg/pytorch-spline-conv/1.2.2/download/linux-64/pytorch-spline-conv-1.2.2-py38_torch_2.4.0_cu124.tar.bz2
 - jupyter
 - pystackreg
 - pip
 - pip:
   - numba>=0.53.0
   - cellpose[gui]==3.0.7
   # - scipy
   # - opencv-python-headless
   - opencv-python==4.1.2.30
   - scikit-image
   - diplib
   - matplotlib
   - smo
   - seaborn
   # - numpy
   # - natsort
   # - tifffile
   # - tqdm
   - llvmlite
   # - fastremap
   - imagecodecs
   # - pyqtgraph>=0.11.0rc0
   # - google-cloud-storage
   - sphinx>=3.0
   - sphinxcontrib-apidoc
   - sphinx_rtd_theme
   - dask
   - dask_image
   - rich
   - pandas
   - nd2
   - pytest
   --extra-index-url https://data.pyg.org/whl/torch-2.4.1+cu124.html
   - pyg_lib
   - torch_scatter
   - torch_sparse
   - torch_cluster
   - torch_spline_conv
   # - record-keeper
   # - faiss-gpu #faiss-cpu (on windows)
   # - python-dotenv
   # - hydra-core==1.1.0.dev5
   # - wandb
