name: cp_dock
channels:
 - nvidia/label/cuda-12.4.1
 - nvidia
 - pyg
 - pytorch
 - conda-forge
 - metric-learning
dependencies:
 - python=3.8.13
 - cuda-toolkit
 - pytorch=2.4.1
 - torchvision=0.19.1
 - torchaudio=2.4.1
 - pytorch-cuda=12.4
 - pytorch-metric-learning=1.3.0
 - torchmetrics=0.6.0
 - pytorch-lightning=1.4.9
 - pyg
 - pytorch-sparse
 - pytorch-cluster
 - pytorch-scatter
 - pytorch-spline-conv
 - jupyter
 - pystackreg
 - pip
 - pip:
   - numba>=0.53.0
   - cellpose[gui]==3.0.7
   # - scipy
   # - opencv-python-headless
   - opencv-python==4.1.2.30
   - scikit-image
   - diplib
   - matplotlib
   - smo
   - seaborn
   # - numpy
   # - natsort
   # - tifffile
   # - tqdm
   - llvmlite
   # - fastremap
   - imagecodecs
   # - pyqtgraph>=0.11.0rc0
   # - google-cloud-storage
   - sphinx>=3.0
   - sphinxcontrib-apidoc
   - sphinx_rtd_theme
   - dask
   - dask_image
   - rich
   - pandas
   - nd2
   - pytest
   # - record-keeper
   # - faiss-gpu #faiss-cpu (on windows)
   # - python-dotenv
   # - hydra-core==1.1.0.dev5
   # - wandb
